spring:
  datasource:
    url: jdbc:mysql://localhost:3306/remembering
    username: felici
    password: ekfvod2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  security:
#    user:
#      name: admin
#      password: 2222
#      roles: USER, ADMIN
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  config:
    activate:
      on-profile: prod

#  spring:
#    mvc:
#      static-path-pattern=/content/**:

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

#jwt:
#  issuer: jykim00c@gmail.com
#  secret_key: 12345678

